name: CI/CD with ArgoCD

on:
  push:
    branches: [main]

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Log in to DockerHub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/node-app:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/node-app:latest

      - name: Update k8s manifest image tag (optional - if using version tags)
        run: |
          sed -i "s|image:.*|image: ${{ secrets.DOCKER_USERNAME }}/node-app:latest|" k8s/deployment.yaml
          git add k8s/deployment.yaml
          git commit -m "Update image tag"
          git push
