name: CI/CD with ArgoCD

on:
  push:
    branches: [main]

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Log in to DockerHub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Build and push Docker image
        run: |
          VERSION=$(date +%s)  # or use git commit hash, semantic versioning, etc.
          docker build -t ${{ secrets.DOCKER_USERNAME }}/node-app:$VERSION .
          docker push ${{ secrets.DOCKER_USERNAME }}/node-app:$VERSION

          # Optionally also push latest for backward compatibility
          docker tag ${{ secrets.DOCKER_USERNAME }}/node-app:$VERSION ${{ secrets.DOCKER_USERNAME }}/node-app:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/node-app:latest

      - name: Update image in deployment.yaml and push to repo
        run: |
          echo "🔍 Showing current image in deployment.yaml:"
          cat k8s/deployment.yaml

          echo "🔧 Updating image line..."
          sed -i "s|image: .*$|image: ${{ secrets.DOCKER_USERNAME }}/node-app:latest|" k8s/deployment.yaml

          echo "✅ After update:"
          cat k8s/deployment.yaml

          git config --global user.email "ayoub_mentag@um5.ac.ma"
          git config --global user.name "Ayoub-Mentag"
          git remote set-url origin https://x-access-token:${{ secrets.GH_PAT }}@github.com/Ayoub-Mentag/ci-cd-node-app.git

          git add k8s/deployment.yaml
          git diff --cached --quiet || git commit -m "Update image tag"
          git push origin main
